### ISSUE TITLE
Requesting for training code

### ISSUE THREAD

**Issue by cth127** [jsavelka/luima_sbd#3]
Dear jsavelka.

Hi, I'm Taehun, M.S. Student at Korea University. 

I'm currently developing a rule-based sbd algorithm and writing a research paper. To make a valid comparison, I'm trying to reproduce multiple rule-based/probabilistic sbd algorithms. I also tried to reproduce your crf model with your data, but I failed. (maybe because of hyper-parameters or preprocessing)

If you don't mind, I want to receive your training code.

Best,

Taehun

**Comment by jsavelka** [comment]
Hi Taehun,

you are referring to the data at https://github.com/jsavelka/sbd_adjudicatory_dec?

I may still have the code I used for training but it will probably not be in great shape.

Best.

j

**Comment by cth127** [comment]
Hi, 

Yes, I tried to use that data.

It's okay. I want to check some details like hyper-parameters or data processing procedure, etc.

I'd be really thankful if you can share your code.

**Comment by jsavelka** [comment]
Ok, I will create a private repo with what I have and invite you.
j

**Comment by cth127** [comment]
Thanks a lot 👍
